/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#005d90',
        'primary-container': '#0077b6',
        'on-primary': '#ffffff',
        'on-primary-container': '#f3f7ff',
        'primary-fixed': '#cde5ff',
        'surface': '#f9f9f9',
        'surface-bright': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f4',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-dim': '#dadada',
        'surface-variant': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#404850',
        'inverse-surface': '#2f3131',
        'outline': '#707881',
        'outline-variant': '#bfc7d1',
        'tertiary': '#755b00',
        'tertiary-container': '#d2a500',
        'tertiary-fixed': '#ffdf90',
        'tertiary-fixed-dim': '#f0c12c',
        'secondary-container': '#dcdddd',
        'secondary': '#5d5f5f',
        'error': '#ba1a1a',
        'gold': '#C5A059',
        'azure': '#0077B6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'unit': '8px',
        'section-padding': '120px',
        'gutter': '32px',
        'margin-x': '80px',
        'container-max': '1440px',
      },
      fontFamily: {
        serif: ['Cinzel', 'Noto Serif', 'serif'],
        sans: ['Manrope', 'sans-serif'],
        display: ['Cinzel', 'Noto Serif', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'display': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'h1': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '400' }],
        'h2': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'h3': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      boxShadow: {
        'sunlight': '0 20px 40px rgba(0,0,0,0.04)',
        'elevated': '0 20px 40px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}
